// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3EpnjSwQeDUhYxZjpdkWrqzIH49VTvG0',
    appId: '1:14737644369:web:f2b476b13cadaaa7bb9170',
    messagingSenderId: '14737644369',
    projectId: 'flutter-sample-6f548',
    authDomain: 'flutter-sample-6f548.firebaseapp.com',
    storageBucket: 'flutter-sample-6f548.appspot.com',
    measurementId: 'G-0GYM60XQZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZBU2HQ8X-m1HAhLEmeP7cU57cxpfpIcs',
    appId: '1:14737644369:android:65f27fb3e8beda0ebb9170',
    messagingSenderId: '14737644369',
    projectId: 'flutter-sample-6f548',
    storageBucket: 'flutter-sample-6f548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWTwmPoB7Ev3yqThzGdJr4XbFQghV5Wvc',
    appId: '1:14737644369:ios:814f49c7b3add274bb9170',
    messagingSenderId: '14737644369',
    projectId: 'flutter-sample-6f548',
    storageBucket: 'flutter-sample-6f548.appspot.com',
    iosBundleId: 'com.example.flutterSample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWTwmPoB7Ev3yqThzGdJr4XbFQghV5Wvc',
    appId: '1:14737644369:ios:2bf5268bc2137b54bb9170',
    messagingSenderId: '14737644369',
    projectId: 'flutter-sample-6f548',
    storageBucket: 'flutter-sample-6f548.appspot.com',
    iosBundleId: 'com.example.flutterSample1.RunnerTests',
  );
}
